version: '3.9'

name: meetmap

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ./dockerfiles/frontend/Dockerfile
      context: .
    environment:
      - PORT=${FRONTEND_PORT}
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  postgres:
    container_name: postgres
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrate_tables:
    container_name: migrate_tables
    restart: no
    env_file:
      - .env
    build:
      dockerfile: ../dockerfiles/migrate_tables/Dockerfile
      context: backend
    depends_on:
      postgres:
        condition: service_healthy

  server:
    container_name: server
    build:
      dockerfile: ../dockerfiles/server/Dockerfile
      context: backend
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${SERVER_PORT}"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: