version: '3.9'

name: meetmap

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${pg_name}
      - POSTGRES_USER=${pg_user}
      - POSTGRES_PASSWORD=${pg_password}

  server:
    env_file:
      - backend/server/config.yaml
    container_name: server
    build:
      dockerfile: server/Dockerfile
      context: backend
    restart: always
    environment:
      - PORT=${server_port}
    ports:
      - "${server_port}:${server_port}"
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    depends_on:
      - postgres
  