"""empty message

Revision ID: e25606391abb
Revises: f130a90efd0f
Create Date: 2024-11-29 19:17:07.831161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25606391abb'
down_revision: Union[str, None] = 'f130a90efd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('placemarks', column_name='create_user_id', new_column_name='user_id')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('placemarks', column_name='user_id', new_column_name='create_user_id')
    # ### end Alembic commands ###
